# Generated by Django 5.1 on 2024-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_head', models.CharField(max_length=100)),
                ('notification_body', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='admin', max_length=10),
        ),
    ]
