# Generated by Django 5.1 on 2024-09-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_notification_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sem',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
