# Generated by Django 5.1 on 2024-09-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_subject_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='batch',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.CharField(max_length=40),
        ),
    ]
