# Generated by Django 5.1 on 2024-09-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_attendance_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='sem',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
