# Generated by Django 5.1 on 2024-09-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0009_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("document", models.FileField(upload_to="documents/")),
            ],
        ),
    ]
